version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - cd web
      - echo updating site content ...
      - aws s3 sync . s3://${WWW_BUCKET}
      - echo Invalidating cache ...
      - aws cloudfront create-invalidation --distribution-id ${WWW_CLOUDFRONT_DIST_ID} --paths "/*";
      - aws cloudfront create-invalidation --distribution-id ${ROOT_CLOUDFRONT_DIST_ID} --paths "/*";

  post_build:
    commands:
      - echo Build finished $(date)
